### ISSUE TITLE
Vent outputs incorrect _eventname in data._vent_log table

### ISSUE THREAD

**Issue by sambuds** [hyperledger/burrow#1087]
The `_eventname` column in the `_vent_log` contains the table name. It should instead have the actual event name e.g. `LogUserAccountCreation`.

**Comment by silasdavis** [comment]
This is because the `eventName` in the main loop `SetBlock` is actually the table name so: https://github.com/hyperledger/burrow/blob/develop/vent/sqldb/sqldb.go#L364 inserts the table name where the event name was expected.

The `eventTables` is correctly indexed in the map by the tables names (after my previous refactor).

We have access to the event name (if the log relates to an event rather than another action) via the `row.RowData`, originally assigned here: https://github.com/hyperledger/burrow/blob/develop/vent/service/decoder.go#L28 

Note the event name is included in the log in the `jsonData` (which is the serialised `RowData`).

If we want to have the event name as a top-level columned (probably useful for searching and joins) then we just need to pull it from `RowData` (we can use nil when it is not available.)
