### ISSUE TITLE
[Core] Implement IBC Protocol

### ISSUE THREAD

**Issue by grandbaiyi** [hyperledger/burrow#1130]
Has Burrow implemented the IBC protocol? I'm looking for an ethermint alternative that can connect to cosmos hub's ethereum.

Thanks.

**Comment by gregdhill** [comment]
Not yet @grandbaiyi, but I believe it is planned - we should probably mark it on the [roadmap](https://wiki.hyperledger.org/display/HYP/2019+Q2+Hyperledger+Burrow) (cc: @silasdavis @seanyoung). In the meantime, we'd appreciate any help kick-starting work on this!

**Comment by grandbaiyi** [comment]
Hi @gregdhill 
If I want to integrate the current IBC into Burrow to complete the verification of POC, what should I do? I think I should first add Cosmos-SDK to this project. But I don't know how difficult it is to do this work. Can you give some advice about this? Thank you very much!

**Comment by silasdavis** [comment]
@grandbaiyi as far as I am aware (can see with brief search) IBC support has not yet landed in the Cosmos-SDK.

The Ethermint zone is not a thing yet either as far as I know.

We fully intend to ship IBC support so that Burrow can act as a Cosmos Zone validator. There is stuff we could do now to build support by looking at the whitepaper, but it would be quite speculative. We would need to adjust our types and machinery once Cosmos is live (should be March this year...) but there is still stuff we could usefully build now if someone (like you :) ) is willing to do some of the work. Failing that we will probably wait until some time post-launch before we start building cross-chain packet support.

**Comment by silasdavis** [comment]
I'm going to close this for now. When the time comes we can add some specific implementation issues.

**Comment by glandua** [comment]
I am curious about if/how this is still active.  We are looking at cross chain communication with hyperledger projects (indy and aries) and curious about if this made it into the IBC spec.

**Comment by gregdhill** [comment]
It is still on the roadmap @glandua, please checkout the open project [here](https://github.com/hyperledger/burrow/projects/7). Progress is slow at the moment due to other commitments, but if you are willing to help out it would very much be appreciated!
