### ISSUE TITLE
Stack too deep issues

### ISSUE THREAD

**Issue by stanta** [hyperledger/burrow#1178]
Hi, @benjaminbollen!
Do you continue work on Burrow?
We have a lot of "Stack too deep" issues in our project, and looks to move from classical EVM to Burrow.  This issues really depends on number of DUP commands limit. It have sense for miner's economy limitations in public Ethereum, but no senses for corporate applications.
https://github.com/hyperledger/burrow/blob/0a078b4f3f29f03d9ad573d8dc164f5ee38ea8d3/execution/evm/asm/opcodes.go#L154

Seems as you copypasted that code from original EVM, but do you plan to remove this and same restrictions in Burrow?

**Comment by silasdavis** [comment]
Burrow actually has a dynamically allocated stack depth unlike standard ethereum, so you can have a stack that is deeper than 1024.

However the stack too deep error is poorly named, since it does not indicate breaching the stack depth limit at all, rather it means that the function has more than 16 arguments and so cannot pull all of the memory references it needs off the stack.

As you identify if there were more `DUPX` opcodes this limit could be raised. However, assuming you are using Solidity additional `DUPX` opcodes would need explicit support from the Solidity compiler. Even if you are considering calling directly with assembly there would the question of where to put these opcodes (there is no space consecutively which is how all the other variable opcodes work) so they would have to be put elsewhere.

Insofar as our EVM support goes I would not want to get into the business of introducing adhoc fixes that diverge from the EVM spec at such a low level. A better solution might be have a `DUPN` opcode that gives arbitrary lookback. To not have this though was a design choice/flaw of the EVM.

A workaround that other EVM uses use is to instead pass a dynamic array of arguments. Another option is to use some lower level calls to pass a struct, see: https://ethereum.stackexchange.com/questions/65980/passing-struct-as-an-argument-in-call

I believe that there are some proposed changes to Solidity to allow for struct calling. This is something that is perfectly doable at the EVM level already. See: https://medium.com/@dillonsvincent/solidity-enable-experimental-abiencoderv2-to-use-a-struct-as-function-parameter-27979603a879

I am closing this for now, but happy to reopen if there is something more we could sensibly do in Burrow.

**Comment by stanta** [comment]
Thank you Silas! Where can I find compiler to compile Solidity files for Burrow?

**Comment by silasdavis** [comment]
Just grab the standard solidity compiled `solc`: https://github.com/ethereum/solidity/releases

`burrow deploy` will use whatever `solc` you have on your path.

**Comment by stanta** [comment]
hmm it have all restrictions of public Ethereum (stack restricted by 16 values, square growth of gas consumption for memory variables).
How to avoid this to compile for Burrow?

**Comment by silasdavis** [comment]
Burrow does not charge gas - the `GasLimit` can be set on transactions to bound computation, but there is no fee, operation all cost 1 gas, and you can set it to whatever you like.

As I said, with the `DUP16` limit - this is something that is baked into the EVM and this would need support from the compiler. Even then just raising the limit would not be a very good solution.

A much better way to solve this, which I think you can use now is described here: https://medium.com/@dillonsvincent/solidity-enable-experimental-abiencoderv2-to-use-a-struct-as-function-parameter-27979603a879

If you have a function with a lot of arguments then define a struct with each argument as a field and have it take the struct as a single argument. This will bypass any limit on `DUPX`.

Functions with anywhere near 16 arguments are almost certainly a bad smell in your code anyway - using a struct means you can group them and avoid accidentally calling with the wrong arguments if the order or number of arguments changes in the future, using a struct effectively gives you named arguments.

**Comment by j-h-scheufen** [comment]
@stanta As Silas said, Burrow does not have its own compiler, but relies on the standard Solidity compiler (solc), so the "stack too deep" error needs to be tackled in your source code. There are multiple ways to do this:
- Enable abiencoderv2 (see @silasdavis comment above) and group fields into structs
- Reduce the number of local variables in the function
- Structure the single function into multiple functions
If you google https://www.google.com/search?q=stack+too+deep+solidity&rlz=1C5CHFA_enUS781US781&oq=stack+too+deep you can find a lot of articles where people have faced this issue and describe solutions.

**Comment by stanta** [comment]
Your answer seems like sarcasm ))) 
Functionality of Burrow seems useless without of compiler... Do you plan to develop own compiler or enhanced version of Solidity (or Vyper or same)  compiler to avoid restrictions of original ?

**Comment by silasdavis** [comment]
> Your answer seems like sarcasm 
No sarcasm.

We do not plan to develop our own compiler because one exists: https://github.com/ethereum/solidity. Avoiding the restrictions of the original as you suggest would break compatibility with the EVM specification which we do not intend to do.

`burrow deploy` will use the local `solc` to compile source code or you can compile it yourself.

**Comment by stanta** [comment]
Sorry, but in this case I can't see any useful variants to using Burrow in enterprise blockchain development.

**Comment by silasdavis** [comment]
In this case, I would point out by your reasoning neither does Parity, Quorum, or Pantheon. None of these make ad hoc changes to the Ethereum ABI specification. It's not perfect, but it is not the place of implementations to make short-sighted highly local changes like this.

If you have ideas for improving the ABI I suggest you look into the Ethereum 2.0 process.

**Comment by stanta** [comment]
they don't plan extend solidity too :(

**Comment by stanta** [comment]
@silasdavis , What about using Webassembly to compile smart contracts in Burrow, like EWASM?
