### ISSUE TITLE
[RPC] Swaggerize

### ISSUE THREAD

**Issue by gregdhill** [hyperledger/burrow#1200]
By strictly defining our RPC interface via Swagger/OpenAPI we can simplify how developers may integrate with Burrow and also prevent issues like #1182.

**Comment by silasdavis** [comment]
I wonder if would be able to use: https://github.com/googleapis/gnostic

Under this model our primary artefact would be a swagger def from which we would generate protobuf files. My feeling is this would be difficult to introduce since we make heavy use of gogoproto for our types and share many of our in-memory types with our RPC types. It would be worth experimenting with at least. Perhaps for RPC query where we currently provide both a GRPC and a HTTP version.

If might want to replace our hand-rolled-from-Tendermint HTTP library with a swagger generated and service exactly the same endpoints over rpcquery....

**Comment by compleatang** [comment]
++ on moving the query rpc to swagger generated HTTP / JSON library.

**Comment by gregdhill** [comment]
One suitable alternative would be [OpenRPC](https://github.com/open-rpc/spec), which I have already been working with for the [Web3 RPC](https://github.com/hyperledger/burrow/pull/1238).

**Comment by silasdavis** [comment]
This I think would still be useful to do (i.e. generate our HTTP end points) but given they are peripheral to main GRPC end points it doesn't feel like it has enough value.

We may want to re-open a more specific ticket - e.g. 'generate rpc/query HTTP end points from GRPC definitions'
