### ISSUE TITLE
Nested caching

### ISSUE THREAD

**Issue by lebdron** [hyperledger/burrow#1328]
There is an example of creating nested caches in `CallContext` implementation. 

First a cache is created in `Deliver` method.
https://github.com/hyperledger/burrow/blob/5ab1874ee63bc812c50c1d66a1474b19bddff541/execution/contexts/call_context.go#L124
It is then passed to `EVM`.
https://github.com/hyperledger/burrow/blob/5ab1874ee63bc812c50c1d66a1474b19bddff541/execution/contexts/call_context.go#L222
Where a `CallFrame` is created.
https://github.com/hyperledger/burrow/blob/5ab1874ee63bc812c50c1d66a1474b19bddff541/execution/evm/evm.go#L82
And then this cache is wrapped in another cache again.
https://github.com/hyperledger/burrow/blob/5ab1874ee63bc812c50c1d66a1474b19bddff541/execution/engine/call_frame.go#L28

Is this behavior expected? It is not clear whether a cache should be created in `CallFrame`.

**Comment by silasdavis** [comment]
Thanks for raising this issue. Good to see people deep in the burrows...

It is a little misty but I seem to remember considering this and accepting it at the time.

As you point out we have a redundant double-cache-wrapping initially. There are a few of things at play:

1. The caller of state-mutating function is _meant to_ (by design) control whether they flush the cache to the next state up (the backend), so they generally need to allocate the cache. So we pass in the `txCache` and it's up to `CallContext` to decide whether to persist the updates.

2. `CallFrames` do in general need to cache-wrap (in general) so we can abandon changes (from an entire subtree of the call graph) when there is an exception.

3. From a segregation standpoint `CallFrame` is meant to be an abstraction belonging to the `execution` subsystem. We do not want the caller to create it really, because it is more flexible if they can pass in any `acmstate.ReaderWriter`. But `engine.State` needs a `CallFrame` so we need to do the conversion (i.e. wrapping).

In the code your reference the three concerns above lead us to allocating an additional unnecessary cache, but this is motivated by the isolation principle of the current design.

I'm open to suggestions but it seemed like premature optimisation to try to change the design just for the sake of avoiding allocating another `map`. Note also the caches have pointer values so the extra GC pressure is not going to be huge. I doubt this is the most inefficient thing we do by some margin :)
