### ISSUE TITLE
File permission issue when running `burrow configure`

### ISSUE THREAD

**Issue by weeix** [hyperledger/burrow#1402]
Hi,

I'm trying to follow the tutorial. However, when I run `burrow configure`, an error message about incorrect file permission appeared:

> $ ./burrow.exe spec -p1 -f1 | ./burrow.exe configure -s- > burrow.toml
> could not generate GenesisDoc from GenesisSpec using MockKeyClient: could not create Account from template: file C:\\burrow\\.keys\\data/A90572FACA634E797FE85FBBCDBB5034A27D0FE6.json should be accessible by user only

I tried changing `C:\burrow\.keys` folder, subfolders and files permission to only be accessible by my account but the same error message still persist:

![image](https://user-images.githubusercontent.com/6592791/90233682-b4c45a00-de48-11ea-9ae7-280569134c7b.png)

Any help  will be appreciated. Thank you.

**Comment by silasdavis** [comment]
This is us just not supporting windows very well. `burrow keys server --allow-bad-perms` would solve this with a standalone keys server. You'd need to run that command in one terminal, then run the original command sequence with `burrow configure --keys-url localhost:10997`.

However I would recommend running in an linux-like environment if possible because I'm afraid we do not have the bandwidth to test on windows.
