### ISSUE TITLE
Can I use web3 websocket provider?

### ISSUE THREAD

**Issue by nayuta-ueno** [hyperledger/burrow#1405]
Can I use web3 websocket provider?
I cannot find settings.
https://hyperledger.github.io/burrow/#/reference/web3

**Comment by silasdavis** [comment]
We don't implement the web3 subscriptions service since our underlying state stream is quite different. We do provide a streaming events service over GRPC: https://github.com/hyperledger/burrow/blob/master/protobuf/rpcevents.proto.

It would be possible to provide some elements of the subscription service for compatibility over events. For me personally the GRPC events service is better suited to my needs so I would not be motivated to implement this, but I would accept contributions here.
