### ISSUE TITLE
Is burrow compatible with abigen? (Or: web3 transaction submission issues)

### ISSUE THREAD

**Issue by mhe** [hyperledger/burrow#1412]
I'm working on porting a "native" Ethereum (PoA) program to burrow. That is, we're using a Go program to interact with a network and part of the Go code is (conveniently) generated by [abigen](https://github.com/ethereum/go-ethereum/tree/master/cmd/abigen).

Using the web3 support of burrow, it seems it is possible to "read" from deployed smart contracts. However, for "write"-interaction with a smart contract key material is needed, which does not seem to work. I've tried both "raw" Ethereum private (secp256k1) keys (generated with `burrow keys` and keys generated from geth. In both cases the transaction is not accepted. The burrow node returns the following error: "calculated Rx is larger than curve P".

Is there any way to make abigen-generated code work with burrow for write-interactions?

**Comment by silasdavis** [comment]
I have recently fixed various issues with our secp256k1 support in this PR: https://github.com/hyperledger/burrow/pull/1420. I have a hunch that what you have seen may have been due to us using compressed secp256k1 public keys whereas Ethereum standardises on uncompressed. I have since moved us to use uncompressed keys and fixed a couple of other things. The reason this has not come up before is the vast majority of users were using us with ed25519 keys before we had web3 support (which is still experimental).

I'd be interested to hear how you get on with this, but it would really help if you could provide a failing Go test in Burrow if we are going to get anywhere quickly with this.

**Comment by silasdavis** [comment]
You have been seeing issues caused by: https://github.com/hyperledger/burrow/pull/1460

**Comment by silasdavis** [comment]
Can reopen if issues persist
