### ISSUE TITLE
[RPC] Implement as much as we can of the web3 HttpProvider specification

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#331]

**Comment by ryepdx** [comment]
Digging into using eris-db as the federated chain solution for an EVM-based project I've been working on. Will `eth_sendRawTransaction` be one of the implemented endpoints? We're using a client-side library to sign Ethereum transactions at present, and I noticed that the Tendermint transactions eris-db uses appear to have a different structure. Just wondering to what degree I should count on eris-db acting as a drop-in replacement for geth upon the completion of this issue.

**Comment by benjaminbollen** [comment]
Thanks @ryepdx! We will work in two steps: first detail and decide what the maximal support we can provide in this respect is. Note that we support the ethereum protocol, and as such solidity contracts can be compiled as normal and run against the eris chains.  However in order to provide some of the features unique to the eris chain (no proof of work and transaction finality; bonding of validators, etc) makes that these two fundamentally different chains (eth public chain vs eris) cannot be treated at all levels as the same.

We understand the value to our users to drive rpc differences down to an absolute minimum.  So we will take this first step very serious and look for the best compromise.  The second step is of course, implementing this proposal.  You can expect to follow this discussion in more detail this week on this and possible linked issues.

With respect to `eth_sendRawTransaction`, there are two ways we can consider this:

1. evaluate switching our transaction format over to the Ethereum formulation, under the condition that the additional transactions we require for, eg bonding, permissions etc have a clean extention on the Ethereum transaction format.

2. provide a new eris transaction type that wraps an Ethereum public chain transaction formulation.

Note that in both cases we will regardless need to look at providing support for secp256k1 signing of transactions; eris transactions are signed with ed25519.

We cannot stress enough how important it is for us to not create different standards as this burdens the innovation within the community.  Regardless, I hope from the above it is already clear this is tangled into a bigger decision than merely providing an additional set of RPC endpoints.  We really welcome our users and the community to join us here in this discussion.

Hope that helps,
Ben

**Comment by AFDudley** [comment]
@ryepdx hi. How are you creating the Txs before you sign them and push them?

**Comment by ryepdx** [comment]
Thanks for the prompt and thorough reply, @benjaminbollen. Much appreciated.

@AFDudley: To create transactions for signing, we're using [eth-lightwallet](https://github.com/ConsenSys/eth-lightwallet)'s `txutils.functionTx` on the client and [web3.py](https://github.com/pipermerriam/web3.py)'s `sendTransaction` on the server.

**Comment by ryepdx** [comment]
To further respond to @benjaminbollen: I think either of those options are fine. Both would lend themselves rather easily to clean interaction with the Ethereum tools already out there, with #1 probably providing the easiest transition for projects built with the Ethereum toolchain in mind.

**Comment by VoR0220** [comment]
@silasdavis @benjaminbollen @ryepdx 

I've compiled this list of JSON-RPC methods that are reasonable for us to implement:

Fluff bits:
[web3_clientVersion](https://github.com/ethereum/wiki/wiki/JSON-RPC#web3_clientversion)
[web3_sha3](https://github.com/ethereum/wiki/wiki/JSON-RPC#web3_sha3)
[net_version](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version)
[net_listening](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_listening)

Medium Importance:
[net_peerCount](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_peercount)
[eth_getTransactionByHash](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash)
[eth_getBlockByHash](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash)
[eth_getBlockByNumber](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber)
[eth_blockNumber](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_blocknumber)
[eth_getBalance](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getbalance)
[eth_getTransactionCount](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactioncount)

High importance:
[eth_getStorageAt](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getstorageat)
[eth_getCode](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getcode)
[eth_sign](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign)
[eth_sendTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction)
[eth_sendRawTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransaction)
[eth_getTransactionReceipt](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt)
[eth_call](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call)
[eth_newFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter)
[eth_newBlockFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newblockfilter)
[eth_newPendingTransactionFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter)
[eth_uninstallFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_uninstallfilter)
[eth_getFilterChanges](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges)
[eth_getFilterLogs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterlogs)
[eth_getLogs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs)

My recommendation is to start with the ones of highest importance that carry the most utility and that we in many ways have already implemented. Then move onto those of medium importance. And then finally the fluffy bits.

**Comment by silasdavis** [comment]
closed by #1238 :tada:
