### ISSUE TITLE
Update keys in sNatives PermsMap to permit/improve sNatives access from Solidity

### ISSUE THREAD

**Issue by jasonklein** [hyperledger/burrow#417]
The keys in `PermsMap` used to identify the sNatives functions at https://github.com/eris-ltd/eris-db/blob/master/manager/eris-mint/evm/snative.go#L55 are the signatures of functions identical to those in the `Permissions` contract at https://github.com/eris-ltd/eris-pm/blob/master/tests/fixtures/app33-evm_connection_edb_permissions_and_roles_layer/permissions.sol.

Please update the keys to represent (with respect to Solidity):
- a `set_global` function that takes 2 arguments, not three: `function set_global(uint64 permFlag, bool value) constant returns (uint64 pf)`
  - 🚨  this is the most immediately requested change because the inconsistency appears to render `set_global` unreachable from a Solidity contract
- functions that set the type for the `permFlag` argument to `uint64` rather than `int` (to be consistent with `PermFlag` in https://github.com/eris-ltd/eris-db/blob/master/permission/types/permissions.go#L17)
- functions with names that are camelCase rather than snake_case
  - `has_base` -> `hasBase`
  - `set_base` -> `setBase`
  - `unset_base` -> `unsetBase`
  - `set_global` -> `setGlobal`
  - `has_role` -> `hasRole`
  - `add_role` -> `addRole`
  - `rm_role` -> `rmRole`

**Comment by VoR0220** [comment]
fairly sure I've completed this but it is a breaking change...cool if I just put the PR up in a "hold onto this until 0.17.0" branch?

**Comment by silasdavis** [comment]
We need to to introduce the permissions stub contract as a first-class asset in eris-db, and automate it so we can be more certain the snatives permissions map matches the contract. It's not good that the permissions map is just some alien reference.

The primary issue here is the inaccessibility of `set_global`. I am reluctant to make cosmetic changes to the casing of the function names that will break backward compatibility, is there a strong reason to do this?

You are correct on the `uint64` point, but again I am reluctant to change the signatures of the working methods for little benefit. Bear in mind that since a PermFlag bitfield is really a way of encoding a more complex type into an integer being slightly tighter on the outer type seems to buy us rather less than it would if we were representing a strictly non-negative number.

Personally I think the permissions interface could do with a more significant overhaul and no expose PermFlags at all (though it could still use them internally), and rather a more simple-minded interface that allows you to set flags on a permissions object. Currently the bit-twiddling approach allows you to set unsupported values and requires knowledge of the permissions representation that seems unnecessary...

**Comment by silasdavis** [comment]
Serviced/superceded by #500
