### ISSUE TITLE
Bad RPC call preventing chain communication

### ISSUE THREAD

**Issue by sTingley** [hyperledger/burrow#429]
Hi,

We are noticing that chains 'break', rather we cannot further communicate with a chain, deploy contracts etc. after it receives a bad request. From examining the chain logs, it seems that there is an issue setting the state hash because of a nonce error/invalid tx.

chain logs:
[chain logs.txt](https://github.com/eris-ltd/eris-db/files/664540/chain.logs.txt)

 Due to the bad request, the 'mgGK' var was given an bogus contract address (theAddr).

    {
	console.log("inside the else statement -- isHuman false")
        var theAddr = req.body.gatekeeperAddr;
        var myGK = contractMgr.newContractFactory(myGK_Abi).at(theAddr);
        
        //calling contract functions below
        retrieveData(myGK, function (result) {
            res.json(result);
        });
    }

**Comment by benjaminbollen** [comment]
_First hypothesis_: due to constraints in the construction of persistence of the state db, upon committing a block and saving it, the references to the cached copy of older blocks of the state, might be void for the codepath used by RPCv0  (to-be-deprecated but still used by JS libs). This would panic the endpoint on 1337, blocking all further communication with it.
_Validation of hypothesis_: Construct client test and review mutex structure on old code path.

**Comment by compleatang** [comment]
very old issue. closing
