### ISSUE TITLE
Subscriptions reaped unexpectedly

### ISSUE THREAD

**Issue by devilgags** [hyperledger/burrow#439]
I have my blockchain running locally . I was using **node-json-rpc** module to make rpc calls . I was able to make few calls like erisdb.getBlockchainInfo. 
I tried the **erisdb.eventSubscribe** call :
```
client.call(
  {
    "jsonrpc": "2.0", "method": "erisdb.eventSubscribe", "params": {
      "event_id": "NewBlock"
    }, "id": "0"
  },
```
 
and it successfully returned a **sub_id** to me :
```
{ result: { sub_id: '7878EB2ECC668AEE19D958B89C4ED6E145D9298E91366D67F93CD2A20E995829' },
  error: null,
  id: '0',
  jsonrpc: '2.0' }
```

I used that **sub_id** to invoke **erisdb.eventPoll**  call :
```
client.call(
  {
    "jsonrpc": "2.0", "method": "erisdb.eventPoll", "params": {
      "sub_id":"7878EB2ECC668AEE19D958B89C4ED6E145D9298E91366D67F93CD2A20E995829"
    }, "id": "1"
  },
```

but it is giving the following **error** : 
```
{ result: null,
  error:
   { code: -32603,
     message: 'Subscription not active. ID: 7878EB2ECC668AEE19D958B89C4ED6E145D9298E91366D67F93CD2A20E995829' },
  id: '1',
  jsonrpc: '2.0' }
```
**My eris-db version is 0.12.1.**

**Comment by dharmesh-kh24** [comment]
**eris-db version: 0.12.0**

Facing the same issue when using http instead of rpc.
I did a POST request: 
```
localhost:1337/event_subs/
{
    "event_id": "Account"
}
```
and got response
```
{
  "sub_id": "A0573376A9CDF594B4A0C2E4CB96D8587F2AB581DB5C85BA479D4259DE6D62A2"
}
```
But when I try to eventpoll, 
`GET: localhost:1337/event_subs/A0573376A9CDF594B4A0C2E4CB96D8587F2AB581DB5C85BA479D4259DE6D62A2`, I get 500 Internal Server error.

Blockchain has following error trace:
```
2017/01/11 22:52:14 [Recovery] panic recovered:
GET /event_subs/A0573376A9CDF594B4A0C2E4CB96D8587F2AB581DB5C85BA479D4259DE6D62A2 HTTP/1.1
Host: localhost:1337
Accept: */*
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Dnt: 1
Postman-Token: 27b99b10-03be-945e-2413-f7a093ef056c
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36


Key "id" does not exist
C:/Go/src/runtime/panic.go:458 (0x42c701)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:180 (0x7c44f8)
D:/Go/src/github.com/eris-ltd/eris-db/rpc/v0/restServer.go:252 (0x594d9c)
D:/Go/src/github.com/eris-ltd/eris-db/rpc/v0/restServer.go:64 (0x59c55b)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:97 (0x7c3ea1)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/tommy351/gin-cors/cors.go:77 (0x7d5563)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:97 (0x7c3ea1)
D:/Go/src/github.com/eris-ltd/eris-db/server/server.go:238 (0x585c67)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:97 (0x7c3ea1)
D:/Go/src/github.com/eris-ltd/eris-db/server/server.go:210 (0x585514)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:97 (0x7c3ea1)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/recovery.go:45 (0x7d2e41)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/context.go:97 (0x7c3ea1)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/gin.go:284 (0x7ca115)
D:/Go/src/github.com/eris-ltd/eris-db/vendor/github.com/gin-gonic/gin/gin.go:265 (0x7c99e7)
C:/Go/src/net/http/server.go:2202 (0x656d24)
C:/Go/src/net/http/server.go:1579 (0x6534de)
C:/Go/src/runtime/asm_amd64.s:2086 (0x45dad1)
```

**Comment by silasdavis** [comment]
I ended up answering this on StackOverflow before coming here, so here's my response from there. Could you update as to whether it does seem like your subscription is getting reaped (as outlined below):

We have two different APIs at the moment. The one you are using we call the 'v0' API. It is optimised for long-polling Javascript clients. My guess is that your subscription is getting reaped before a certain hard-coded timeout that happens to be 10 seconds. Have you tried making the `eventPoll` call in quick sucession after the `eventSubscribe` call?

This is the 'v0' reaping function: https://github.com/eris-ltd/eris-db/blob/master/event/event_cache.go#L72. It runs in a loop clearing out old subscriptions that have not been polled recently. If you have waited longer than 10 seconds before polling then your subscription has probably been reaped (deleted).

We have another API optimised for chain administration called the 'tendermint' API (because of its heritage from the Tendermint consensus engine). It is something of a parallel API and it is used by the eris-pm tool. It also has a subscribe method accessible by a websocket endpoint. This might be useful for you because its subscriptions are never reaped.

You could try it out like this:

Start your chain:

    $ eris chains start testchain

Get a simple websocket client:

    $ go get github.com/raphael/wsc
    
Connect to the websocket endpoint:
    
    $ wsc ws://0.0.0.0:46657/websocket
    2017/01/21 01:03:51 connecting to ws://0.0.0.0:46657/websocket...
    2017/01/21 01:03:51 ready, exit with CTRL+C.

Subscribe to the `NewBlock` event by pasting `{ "jsonrpc": "2.0", "method": "subscribe", "params": ["NewBlock"] }` into the terminal as a single line:

    >> { "jsonrpc": "2.0", "method": "subscribe", "params": ["NewBlock"] }

Then you should receive a stream of new block events (about 1 per second) like:

    << {"jsonrpc":"2.0","id":"#event","result":[19 {"event":"NewBlock","data":[1,{"block":{"header":{"chain_id":"testchain","height":206320,"time":"2017-01-21T01:04:01.095Z","num_txs":0,"last_block_hash":"2DB0D0AE6D92DA6DA07F8E7D1605AAB6CB96D8D2","last_block_parts":{"total":1,"hash":"A4AD1708714CF0BE3E5125B65F495DDDFA1ED8D9"},"last_commit_hash":"4C301C0367B7CECDD4E00C955D2F155802B2377E","data_hash":"","validators_hash":"46E43215C6C332446114BF7320D2D007114C5EEB","app_hash":"9A72DE9AAD6BD820A64DB98462CD706594217E1
    << 1"},"data":{"txs":[]},"last_commit":{"precommits":[{"height":206319,"round":0,"type":2,"block_hash":"2DB0D0AE6D92DA6DA07F8E7D1605AAB6CB96D8D2","block_parts_header":{"total":1,"hash":"A4AD1708714CF0BE3E5125B65F495DDDFA1ED8D9"},"signature":"45A6C3D0B0BD380A239F014681A29FD6217B52653CC7FC189FF5B7DC840A61062CF12FC652687A30A5CBBF0270937F32542D6075BA94A12180568560B322EC07"}]}}}]}],"error":""}

You could use a programmatic websocket client of your choice to interact with the chain using this websocket API and your subscriptions will never get reaped.

There is a grand unification of these APIs planned soon that should make them easier to use and better documented.

**Comment by ratranqu** [comment]
@silasdavis, very interesting. What would happen if a client connected through the web socket api disconnects without unsubscribing? will it be prevented to resubscribe upon reconnect (with same ip)? I'm asking because I seem to see that behaviour of not being able to resubscribe in 0.11.4 (haven't dug into it yet) when there is a client disconnect. my current workaround is to stop and start the chain on the node used to access the chain.

**Comment by silasdavis** [comment]
Converting this ticket to a placeholder to look into unexpected reaping, which almost certainly has more to do with timeouts or the Javascript library handling, but this should come under the umbrella of Burrow until such a time there is a viable alternative.

**Comment by compleatang** [comment]
this has all be refactored significantly. closing this ticket for now. if the issue arises again we can reopen
