### ISSUE TITLE
race condition in tests on NewBlock event

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#597]
Race condition in test on new block event for tendermint v0.9.2 on (develop / 0.17)

```
github.com/hyperledger/burrow/rpc/tendermint/test
=== RUN   TestSubscribe
--- FAIL: TestSubscribe (1.01s)
    websocket_client_test.go:298: Continued to see NewBlock event after unsubscribing
```

- `burrow version` 0.17.0

**Comment by silasdavis** [comment]
This test was passing due to a globally scoped timeout that should have been a timeout within the final for loop. It is actually a real fail. The reason is a breaking change in go-rpc:

From ws_client.go:

```go
// Subscribe to an event. Note the server must have a "subscribe" route
// defined.
func (wsc *WSClient) Subscribe(eventid string) error {
	err := wsc.WriteJSON(types.RPCRequest{
		JSONRPC: "2.0",
		ID:      "",
		Method:  "subscribe",
		Params:  map[string]interface{}{"event": eventid},
	})
	return err
}

// Unsubscribe from an event. Note the server must have a "unsubscribe" route
// defined.
func (wsc *WSClient) Unsubscribe(eventid string) error {
	err := wsc.WriteJSON(types.RPCRequest{
		JSONRPC: "2.0",
		ID:      "",
		Method:  "unsubscribe",
		Params:  map[string]interface{}{"event": eventid},
	})
	return err
}
```
Our unsubscribe method takes a 'subscriptionId' parameter, not an 'event' parameter. Before https://github.com/tendermint/go-rpc/commit/e1d5873bdfc95728971a38297ec3150a556397f9 there were no parameter names.

We should call the WriteJSON method ourselves.

**Comment by benjaminbollen** [comment]
so worth updating ours here: https://github.com/hyperledger/burrow/blob/develop/rpc/tendermint/core/routes.go#L42 ?

and carry forward the breaking change?  I'd opt for that over absorbing the breaking change in our code; burrow-client is the foremost user of tendermint rpc for burrow anyways

**Comment by silasdavis** [comment]
fixed in pr
