### ISSUE TITLE
what is difference between Account and PrivAccount?

### ISSUE THREAD

**Issue by ktr0731** [hyperledger/burrow#724]
Burrow has a development RPC `burrow.genPrivAccount` which creates PrivAccount. but I couldn't find the RPC which creates Account.
what is difference Account and PrivAccount? and we can create new Accounts (not PrivAccount) by Burrow RPC?

**Comment by mikemaller** [comment]
I believe all accounts are PrivAccount.  Even new ones.

**Comment by silasdavis** [comment]
In the EVM creating an account is equivalent to giving it a non-zero balance. So in order to 'create' an account `send` to it with a funded account. You can also use a `PermissionTx` to change from the non-default permissions.

PrivAccount generation a private key server side and should probably be considered deprecated.
