### ISSUE TITLE
Roadmap and plans

### ISSUE THREAD

**Issue by paulvi** [hyperledger/burrow#748]
Where is roadmap and future plans for this project?

**Comment by smblucker** [comment]
Roadmap, future plans and other information about the project can be found at:

https://wiki.hyperledger.org/projects/burrow

**Comment by paulvi** [comment]
Thanks

Roadmap is important info to check for any new project,
and usually one can find such link from README

However in this repository development goes not in default branch `master` 
(that is also is displayed by GitHub), but in `develop` branch.  
That let me think that the project is abandoned for first half hour I was studying it.

Maybe you should change default branch in GitHub to be `develop`

![image](https://user-images.githubusercontent.com/1614482/39366339-39d62030-4a66-11e8-8fb7-08253c0d1909.png)

**Comment by silasdavis** [comment]
I agree with your points.

master is still our release branch, the reason is hasn't been merged to recently is stabilising a major refactor. I had been waiting until I was ready to cut the next release before I merged to master (which I plan to do in the next two week sprint, which starts tomorrow). However, I think all that is really required for a merge to master ahead of the release is the updating of some docs. I'll endeavour to do this this week.

I need to update the roadmap on the Hyperledger wiki. Much of it still applies, I have a newer draft internal roadmap for our own network and product much of which are general features for Burrow. I need to add this to the wiki. I will provide a link to the roadmap and wiki from the readme as you suggest.

**Comment by silasdavis** [comment]
added
