### ISSUE TITLE
[consensus] if possible, recover from bad host errors on peers dialing

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#789]
while it is true that DNS propagation is the worst, we should be able to recover from this, or at least eat the error for a predefined set of dials.

```
{"book":".burrow/config/addrbook.json","caller":"service.go:129","component":"Tendermint","impl":"AddrBook","log_channel":"Info","message":"Starting AddrBook","module":"
p2p","run_id":"4778b37f-69eb-11e8-8ec9-fc0450ed4674","scope":"tendermint.NewNode","time":"2018-06-07T00:39:50.283601797Z"}
could not boot Burrow kernel: error launching Tendermint server: error starting Tendermint node: failed to start PEXReactor: Error in address tcp://000000000000000000000
0000000000000000002@002.peers.t2.agreements.network:46656: lookup 002.peers.t2.agreements.network on 10.63.240.10:53: no such host
```

The above error throws and the node's process fails with that error.

**Comment by silasdavis** [comment]
recovering from this would mean trying to recreate the tendermint node object in our kernel boot sequence. It's not actually that unreasonable to require seeds to be present on boot - persistent peers do not need to be - so for the purposes of wiring up a network you can get around this.

There is an interface for dialing peers - as seed, persistent, or otherwise which can make some of this connectivity stuff a bit more dynamic. We should open that up at some point. 

Will close this now but reopen if you've more to say.
