### ISSUE TITLE
[State] burrow rollback

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#815]
As an administrator of a burrow chain, if I have a situation where a node is acting up, I need to be able, at times, to rollback to the blockchain + state to a block which I know is in consensus. 

Currently if we have a catastrophic incident on a node we have to remove it's `.burrow` directory entirely which cause a full resync with the entire chain. For short running chains this isn't a huge issue but fast_sync isn't incredibly fast and it can take upwards of a day or two to fully resync on some longer running chains.

**Comment by silasdavis** [comment]
We are pretty close to having this already on our side of the fence. Tendermint is a bit of moving target but the forensics stuff has the groundwork. We ought to be able to hack it out.

**Comment by silasdavis** [comment]
This is still something we don't strictly have. However I do wonder if it ought to be technically superseded by dump/restore. In either case we are effectively forking the chain. However under this notion of rollback we do preserve the 'good tendermint history'.

I'm inclined to feel like tightening up our dump/restore into a managed forking/chain of chains approach would be a better single direction to focus our efforts, but open to arguments otherwise.

**Comment by compleatang** [comment]
yes. dump @ block(now)-100 + restore would achieve the exact same critical operational management function identified in the ticket, IMV
