### ISSUE TITLE
[ Bug ] SIGILL illegal instruction err 0C2 privileged operation error running Burrow 

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [hyperledger/burrow#905]
-  0.21.0  `burrow version` 
-  go1.10.2   `go version` 
-  linux/amd64 Ubuntu 16.04LTS operating system details 

### What you expected to happen
Build burrow binary and execute to generate burrow.toml and proceed.
### What actually happened
Binary was built and installed, when executed received a SIGILL illegal instruction err 0C2 privileged operation error
###  Steps to reproduction

1. make build_burrow
2. make install_burrow
3. burrow spec -p1 -f1 | burrow configure -s- > burrow.toml

```
burrow spec -p1 -f1 | burrow configure -s- > burrow.toml
SIGILL: illegal instruction
PC=0x735e2e m=0 sigcode=2

goroutine 1 [running, locked to thread]:
< ... > 

SIGILL: illegal instruction
PC=0x735e2e m=0 sigcode=2

< ... >

rax    0xc420245c58
rbx    0x4
rcx    0x14
rdx    0x179ce40
rdi    0xc4207e6030
rsi    0xc420245c58
rbp    0xc420245b48
rsp    0xc420245b18
r8     0x1
r9     0x0
r10    0xc4207e6030
r11    0x1
r12    0xffffffffffffffff
r13    0x2
r14    0x1
r15    0xaa
rip    0x735e2e
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

```

**Comment by seanyoung** [comment]
Unfortunately this is not enough information to debug this. Would it be possible to generate a core file and run gdb on it, and then "disassemble $pc". You might need to set the core ulimit to unlimited with "ulimit -c unlimited"

Since signal is illegal instruction I suspect there is a package which uses new sse instructions or so, for example https://github.com/tmthrgd/go-hex which uses sse instructions which might not be supported on all cpus.
So what cpu are you using? (output of cat /proc/cpuinfo please)

**Comment by GoodFaithParadigm8** [comment]
An ole Pentium 4 that was at one time a decent server. Haven't got around to generating the core file but I'll give it a shot.

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Pentium(R) CPU        G6950  @ 2.80GHz
stepping	: 2
microcode	: 0x11
cpu MHz		: 1330.000
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm popcnt lahf_lm ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid dtherm arat flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 5599.51
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Pentium(R) CPU        G6950  @ 2.80GHz
stepping	: 2
microcode	: 0x11
cpu MHz		: 1330.000
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 2
cpu cores	: 2
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm popcnt lahf_lm ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid dtherm arat flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 5599.51
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by seanyoung** [comment]
go-hex requires at least sse4.1 (it uses the PINSRD instruction).
See here:
https://github.com/tmthrgd/go-hex/blob/master/hex_amd64.go#L29
Now this also looks like it will not work on non-x86; it assumes SSE when AVX is not present, which is not true for e.g. arm.
This needs to be fixed in go-hex.

**Comment by silasdavis** [comment]
Thanks for diagnosis @seanyoung 

go-hex was introduced in large part because it has an an `EncodeUpper` function that gives you upper case hex - which we sort of need for consistency across go-amino and other endpoitns. That combined with an order of magnitude speedup seemed like a good enough reason to use the library. However, this is an unintended consequence, and now we use protobuf we are spending less time than we used to doing hex encoding. I would consider going back to stdlib - I'm not sure how many people this issue effects.

Raised a bug upstream: https://github.com/tmthrgd/go-hex/issues/3

**Comment by seanyoung** [comment]
I've created a PR for go-hex: https://github.com/tmthrgd/go-hex/pull/4
